/**
 * strings.js — 모든 UI 문구를 키-문구로 한 곳에서 관리. 화면 코드는 t('키', { 값 })로만 불러온다.
 *  - 설정값에서 나오는 숫자(유지 시간·바퀴 수·하트 수 등)는 문구에 직접 쓰지 말고 {이름}으로 받아 코드 값을 넣을 것
 *    (유지 시간은 스테이지마다 다름: 3단계 1.2초, 5단계 0.9초 …)
 *  - 용어는 docs/용어집.md를 따른다(게이트→가속 지점, 밸런스→균형 잡기, 이탈→탈선, 턴→커브, 랩→바퀴, 피니쉬→결승선).
 *  - 글꼴 서브셋(tools/make-fonts.py)이 이 파일의 글자를 수집하므로, 문구를 바꾸면 한 번 다시 돌릴 것.
 */
const STRINGS = {
  // ── 이름 ──
  'brand.stem': '떨어진다',
  'brand.name': '떨어진다!!!',

  // ── 공통 ──
  'common.ok': '알겠어요',
  'common.close': '닫기',
  'common.retry': '다시 도전',
  'common.stageSelect': '단계 선택',
  'common.on': '켜짐',
  'common.off': '꺼짐',
  'popup.prev': '이전',
  'popup.next': '다음',
  'aria.howto': '조작법',
  'aria.settings': '설정',
  'aria.back': '뒤로',

  // ── 코스(단계) 이름·소개: 실제 놀이공원 이름은 그대로, 소개는 쉬운 말로 ──
  'stage.1.name': '우방타워랜드',
  'stage.1.motif': '처음 타기 좋은 완만한 코스예요.',
  'stage.2.name': '도투락월드: 급류의 계곡',
  'stage.2.motif': '레일에 매달려 달리는 코스예요. 커브가 많아요.',
  'stage.3.name': '도투락월드: 외줄 타기',
  'stage.3.motif': '외줄 레일 위를 달려요. 좌우 균형이 가장 중요해요.',
  'stage.4.name': '도투락월드: 수직 강하',
  'stage.4.motif': '높은 곳에서 거의 수직으로 떨어져요!',
  'stage.5.name': '자연농원',
  'stage.5.motif': '가장 길고 빠른 코스예요. 끝까지 집중해요!',
  'stage.tutorial.name': '꼬마 열차 연습장',
  'stage.tutorial.motif': '천천히 달리며 조작을 하나씩 연습해요.',

  // ── 타이틀·단계 선택·단계 상세 ──
  'title.start': 'START',
  'title.dock.settings': '설정',
  'title.dock.howto': '조작법',
  'title.dock.tutorial': '연습 코스',
  'title.dock.credits': '크레딧',
  'select.cleared': '완주 {n} / {total}',
  'select.practice': '연습',
  'select.practiceName': '연습 코스 · {name}',
  'select.done': '완료',
  'select.recommend': '추천',
  'select.new': 'NEW',
  'select.best': '최고 {n}',
  'detail.title': '{n}단계',
  'detail.rollbackAuto': '뒤로 미끄러지는 곳이 있어요. 부스터가 쏘아 올려 줘요.',
  'detail.rollbackMash': '뒤로 미끄러지는 곳이 있어요. BOOST를 마구 눌러 올라가요!',
  'detail.topSpeed': '최고속도 {kmh}km/h',
  'detail.derailOn': '탈선 켜짐',
  'detail.derailOff': '탈선 꺼짐',
  'detail.laps': '바퀴 수',
  'detail.lapOption': '{n}바퀴',
  'detail.bestRank': '최고 등급',
  'detail.bestScore': '최고 점수',
  'detail.record': '{cond} · {plays}번 완주',
  'detail.cond': '{laps}바퀴',
  'detail.condOff': '{laps}바퀴 · 탈선 꺼짐',

  // ── 결과 ──
  'result.complete': '완주!',
  'result.firstClear': '처음 완주!',
  'result.newBest': '최고 기록!',
  'result.best': '최고 {n}',
  'result.cond': '{laps}바퀴',
  'result.condOff': '탈선 꺼짐',
  'result.gate': '가속 지점',
  'result.balance': '균형 잡기 (커브 {a}/{b})',
  'result.balancePerfect': '균형 PERFECT ×{n}',
  'result.combo': '콤보 보너스',
  'result.finish': '결승선 보너스',
  'result.mash': '연타 보너스',
  'result.derail': '탈선 ×{n}',
  'result.maxCombo': '최고 콤보',
  'result.balanceAcc': '균형 정확도',
  'result.assist': '도움 가속',
  'result.assistDesc': '속도가 느려져 카트가 밀어 준 시간 비율',
  'result.gateJudge': '가속 지점 판정',
  'result.missed': '놓침 {n}',

  // ── 설정 ──
  'settings.title': '설정',
  'settings.graphics': '그래픽',
  'settings.view': '시점',
  'settings.view.third': '3인칭',
  'settings.view.first': '1인칭',
  'settings.view.thirdDesc': '카트를 뒤에서 봐요. 짜릿할 땐 잠깐 카트 안에서 봐요.',
  'settings.view.firstDesc': '계속 카트에 탄 눈으로 봐요.',
  'settings.sound': '소리',
  'settings.soundDesc': '안 들리면 폰의 무음 모드를 꺼 주세요.',
  'settings.control': '균형 조작',
  'control.twohand': '바 끌기',
  'control.tilt': '기울기',
  'control.twohandDesc': '왼쪽 아래 바를 손가락으로 끌어요.',
  'control.tiltDesc': '폰을 좌우로 기울여요.',
  'settings.derail': '탈선',
  'settings.derailDesc': '커브를 놓치면 레일 밖으로 나가요.',
  'settings.howto': '조작법',
  'settings.credits': '크레딧',
  'settings.tutorial': '연습 코스 다시 하기',

  // ── 그래픽 ──
  'graphics.title': '그래픽',
  'graphics.quality': '화질',
  'graphics.style': '화면 스타일',
  'graphics.quality.low': '낮음',
  'graphics.quality.medium': '보통',
  'graphics.quality.high': '높음',
  'graphics.quality.lowDesc': '오래된 폰에 좋아요. 그림자와 흐림 효과를 꺼요.',
  'graphics.quality.mediumDesc': '대부분의 폰에 알맞아요. 가벼운 효과가 있어요.',
  'graphics.quality.highDesc': '가장 화려해요. 그림자와 빠른 느낌 효과가 있어요.',
  'graphics.style.day': '카툰 낮',
  'graphics.style.toon': '카툰 노을',
  'graphics.style.pastel': '파스텔',
  'graphics.style.standard': '사실적',
  'graphics.style.dayDesc': '맑은 하늘과 구름, 밝고 산뜻한 낮이에요.',
  'graphics.style.toonDesc': '굵은 윤곽선과 노을빛. 빠를 때 모양이 또렷해요.',
  'graphics.style.pastelDesc': '부드럽고 따뜻한 파스텔 색이에요.',
  'graphics.style.standardDesc': '실제 같은 조명과 하늘이에요.',

  // ── 조작법 (가로 폰에서도 4페이지 이하: 항목마다 한두 문장) ──
  'howto.title': '조작법',
  'howto.launch': '출발',
  'howto.launchText': '스타트 바를 아래로 당겼다가 위로 확 밀어요. (키보드: ↓ 꾹 누르고 ↑)',
  'howto.balance': '균형 잡기',
  'howto.balanceText': '왼쪽 바를 끌어 손잡이를 초록 띠 안에 {hold}초 두세요. (키보드: ← →)',
  'howto.boost': '부스트(가속)',
  'howto.boostText': '링이 점선에 닿는 순간 BOOST를 눌러요. (키보드: ↑)',
  'howto.judge': '판정',
  'howto.judgeText': '점수는 PERFECT(완벽) › GOOD(좋음) › MISS(아쉬움) 순이에요.',
  'howto.derail': '탈선',
  'howto.derailText': '커브를 놓치면 하트가 줄고, {hearts}번이면 실패예요. (설정에서 끌 수 있어요)',
  'howto.rollback': '뒤로 미끄러짐',
  'howto.rollbackText': '언덕에서 뒤로 밀려요. 부스터가 쏘아 주거나 BOOST를 마구 눌러요.',
  'howto.view': '시점',
  'howto.viewText': '오른쪽 버튼을 누르면 {sec}초 동안 다른 시점으로 봐요. (키보드: C)',
  'howto.floor': '바닥 표시',
  'howto.floorBoost': '부스트',
  'howto.floorCurve': '커브',
  'howto.floorDrop': '내리막·물',
  'howto.floorBack': '뒤로 미끄러짐',

  // ── 크레딧 ──
  'credits.title': '크레딧',
  'credits.game': '떨어진다!!! RIDE IT · chaechae studio',
  'credits.tester': '테스터 Chaewon',
  'credits.model': '3D 모델',
  'credits.sky': '하늘 이미지',
  'credits.sfx': '효과음',
  'credits.sfxText': 'Nocturnal_Vanguard · rubberduck · Kenney.nl (CC0), 나머지는 직접 만든 소리예요.',
  'credits.font': '글꼴·엔진',
  'credits.fontText': 'Noto Sans KR · Jua (OFL 1.1) · Babylon.js',

  // ── 일시정지·불러오기·실패 ──
  'pause.title': '잠깐 쉬어가요',
  'pause.stage': '{name}',
  'pause.resume': '계속하기',
  'loading.text': '코스터를 준비하고 있어요…',
  'loadError.title': '불러오지 못했어요',
  'loadError.text': '네트워크를 확인하고 다시 해 봐요.',
  'loadError.retry': '다시 시도',
  'fail.title': '아쉬워요, 실패!',
  'fail.text': '탈선을 {hearts}번 해서 멈췄어요.',
  'tutAsk.title': '환영해요!',
  'tutAsk.heading': '연습 코스부터 해 볼까요?',
  'tutAsk.text': '꼬마 열차로 출발, 균형 잡기, 부스트를 하나씩 해 봐요. 1분이면 끝나요.',
  'tutAsk.yes': '해 볼래요',
  'tutAsk.no': '건너뛰기',
  'tutDone.title': '준비 완료!',
  'tutDone.text': '출발부터 결승선까지 모두 해냈어요.',
  'tutDone.go': '1단계 출발',
  'update.toast': '새 버전이 있어요 · 눌러서 새로고침',

  // ── 주행 중 ──
  'hud.lap': '바퀴 {n}/{total}',
  'hud.curve': '커브 {n}/{total}',
  'hud.combo': '콤보',
  'hud.skip': '건너뛰기',
  'hud.lives': '남은 기회',
  'hud.balanceBar': '균형 바',
  'hud.curveLeft': '◀ 왼쪽 커브',
  'hud.curveRight': '오른쪽 커브 ▶',
  'hud.fallbackBar': '바를 끌어 주세요',
  'hud.view': '시점 바꾸기',
  'hud.sound': '소리 켜기·끄기',
  'hud.pause': '일시정지',
  'hud.finish': '결승선',
  'view.first': '1인칭',
  'view.third': '3인칭',
  'start.label': '아래로 당겼다가<br>위로 확 밀어요!',
  'start.keys': '키보드: ↓ 누르고 있다가 ↑로 출발',
  'rb.slip': '뒤로 미끄러져요!',
  'rb.hold': '꽉 잡아요!',
  'rb.mash': '연타!',
  'rb.launch': '쏘아 올려요!',
  'sig.derail': '탈선!',
  'sig.respawn': '다시 출발!',
  'sig.good': '좋아요!',
  'lap.n': '{n}/{total}바퀴',
  'lap.final': '마지막 바퀴!',
  'lap.finish': '완주!',

  // ── 그림 설명 ──
  'diagram.target': '목표',
  'diagram.knob': '내 손잡이',
  'diagram.ring1': '① 링이 줄어들어요',
  'diagram.ring2': '② 점선에 닿을 때',
  'diagram.ring3': '누르면 PERFECT!',
  'diagram.ring4': '노란 띠 안 = GOOD',

  // ── 연습 코스(튜토리얼) ──
  'tut.ok': '해 볼게요!',
  'tut.step.start': '출발',
  'tut.step.balance': '균형 잡기',
  'tut.step.boost': '부스트',
  'tut.step.combo': '함께 하기',
  'tut.step.rollback': '뒤로 미끄러짐',
  'tut.step.finish': '결승선',
  'tut.card.balance': '균형 바 읽는 법',
  'tut.card.boost': '부스트 타이밍',
  'tut.card.combo': '함께 하기',
  'tut.card.rollback': '뒤로 미끄러짐',
  'tut.card.finish': '결승선',
  'tut.lean.keyboard': '<b>← →</b> 키로',
  'tut.lean.tilt': '<b>폰을 기울여서</b>',
  'tut.lean.touch': '왼쪽 아래 <b>바</b>를 끌어서',
  'tut.boost.keyboard': '<b>↑</b> 또는 <b>Space</b>',
  'tut.boost.touch': '오른쪽 아래 <b>BOOST</b>',
  'tut.start.keyboard': '<b>↓</b> 누르고 있다가 <b>↑</b>로 출발!',
  'tut.start.touch': '<b>아래로 당겼다가 위로</b> 확 밀어요',
  'tut.balanceCard': '커브에서는 {lean} <b>손잡이</b>를 <b>초록 띠</b> 안에 두세요. <b>{hold}초</b> 동안 있으면 성공! 진한 띠는 PERFECT(완벽)예요.',
  'tut.balanceNote': '놓치면 탈선할 수 있어요. (설정에서 끌 수 있어요)',
  'tut.balanceBanner': '손잡이를 초록 띠에 {hold}초!',
  'tut.balanceHint': '손잡이를 초록 띠 안으로!',
  'tut.boostCard': 'BOOST 둘레의 링이 줄어들어요. <b>링이 점선에 닿는 순간</b> {boost}! 부스트는 속도를 확 올려 주는 가속이에요.',
  'tut.boostBanner': '링이 닿을 때 {boost}',
  'tut.comboCard': '이번엔 함께! 바는 그대로 두고, 위쪽 링이 닿을 때 {boost}.',
  'tut.comboBanner': '바 유지 + 부스트!',
  'tut.rollbackCard': '언덕에서 <b>뒤로 미끄러져요!</b> {boost}를 <b>마구 눌러</b> 올라가요.',
  'tut.rollbackBanner': '{boost} 마구 누르기!',
  'tut.finishCard': '<b>결승선</b>을 지나면 완주! 링이 닿을 때 누르면 보너스 점수예요.',
  'tut.finishBanner': '결승선을 지나면 끝!',
  'tut.retryEarly': '조금 빨랐어요 — 링이 닿을 때 다시!',
  'tut.retryLate': '조금 늦었어요 — 링이 닿을 때 다시!',
  'tut.retryMissed': '링이 닿을 때 눌러요 — 다시!',
  'tut.retryBar': '바(초록 띠)를 유지한 채로 BOOST!',
  'tut.climbing': '언덕을 올라가요…',
  'tut.fasterMash': '더 빠르게 마구 눌러요!'
};

/** 문구 가져오기 — {이름} 자리를 값으로 바꿈. 키가 없으면 키 그대로 보여 줘서 빠뜨린 걸 바로 알 수 있게 함 */
function t(key, vars) {
  let s = STRINGS[key];
  if (s === undefined) { console.warn('[strings] 없는 키:', key); return key; }
  if (vars) s = s.replace(/\{(\w+)\}/g, (m, k) => (vars[k] !== undefined ? vars[k] : m));
  return s;
}
/** 단계 이름·소개(strings.js의 stage.*) */
const stageName = s => t(s.nameKey);
const stageMotif = s => t(s.motifKey);
window.STRINGS = STRINGS;
window.t = t;
